# -*- coding:utf-8 -*-
# Author:       Casey Sparks
# Date:         February 20, 2025
# Description:  Config file for the pull request labeler action.
# Notes:        Read the [docs](https://github.com/actions/labeler) for configuration settings.
---
# PR type labels
bot:
  - head-branch: ['^dependabot/*']
chore:
  - head-branch:
    - '^chore*'
    - '^dependabot*'
feature:
  - head-branch: ['^feat*']
fix:
  - head-branch: ['^fix*']

# Filetype/language labels
ci: &ci
  - changed-files:
    - any-glob-to-any-file:
      - '.github/config/*'
      - '.github/workflows/*.yaml'
      - '.github/workflows/*.yml'
codeowners: 
  - changed-files:
    - any-glob-to-any-file:
      - './github/CODEOWNERS'
      - './github/codeowners'
dependabot: 
  - changed-files:
    - any-glob-to-any-file: ['./github/dependabot.yml']
documentation:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.md'
      - '**/*README*'
      - '**/doc/**'
      - '**/docs/**'
git:
  - changed-files:
    - any-glob-to-any-file:
      - '**/.git*'
      - '.gitattributes'
      - '.gitmodules'
github:
  - changed-files:
    - any-glob-to-any-file: ['.github/**']
terraform:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.hcl'
      - '**/*.tf'
      - '**/*.tf.json'
      - '**/*.tfvars'
      - '**/*.tfvars.json'
