---
name: 'Terraform'
# Author:       Casey Sparks
# Date:         August 16, 2024
# Description:  Run `terraform validate` against new terraform configs.

on:
  pull_request:
    branches: ['main']
    paths: ['**/*.tf']
env:
  TF_VER: '1.10.5'
jobs:
  terraform_validate:
    name: 'Terraform Validate'
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
    strategy:
      matrix:
        work_dir:
          - 'cloudflare_dns_zone'
          - 'ecr'
          - 'forward_zones'
          - 'hugo_static_site'
          - 's3_artifacts'
    defaults:
      run:
        working-directory: '${{ matrix.work_dir }}'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683'  # v4.2.2
        with:
          fetch-depth: 0

      - name: 'Set up Terraform'
        uses: 'hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd'  # v3.1.2
        with:
          terraform_version: '${{ env.TF_VER }}'

      - name: 'Initialize Terraform'
        run: 'terraform init -backend=false'

      - name: 'Validate Terraform configs.'
        run: 'terraform validate'

  terraform_fmt:
    name: 'Terraform Format'
    if: '${{ github.event_name }} == "pull_request"'
    runs-on: 'ubuntu-latest'
    needs: ['terraform_validate']
    permissions:
      contents: 'write'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683'  # v4.2.2
        with:
          fetch-depth: 0

      - name: 'Set up Terraform'
        uses: 'hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd'  # v3.1.2
        with:
          terraform_version: '${{ env.TF_VER }}'

      - name: 'terraform fmt'
        run: 'terraform fmt --recursive'

      - name: 'Import PGP identity'
        id: 'import_pgp'
        uses: 'crazy-max/ghaction-import-gpg@cb9bde2e2525e640591a934b1fd28eef1dcaf5e5'  # v6.2.0
        with:
          gpg_private_key: '${{ secrets.AUTO_SIGNING_KEY }}'
          passphrase: '${{ secrets.AUTO_SIGNING_KEY_PASSPHRASE }}'
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: 'Commit and push changes'
        uses: 'stefanzweifel/git-auto-commit-action@8621497c8c39c72f3e2a999a26b4ca1b5058a842'  # v5.0.1
        with:
          commit_message: 'ci(terraform): Auto-reformatted Terraform configs.'
          commit_author: '${{ steps.import_pgp.outputs.name }} <${{ steps.import_pgp.outputs.email }}>'
          commit_user_email: '${{ steps.import_pgp.outputs.email }}'
          commit_user_name: '${{ steps.import_pgp.outputs.name }}'
          file_pattern: '*.tf'
