---
name: 'Validate YAML files'
# Author:       Casey Sparks
# Date:         June 06, 2024
# Description:  Run yamllint against all YAML files in the repository.

on:
  pull_request:
    branches: ['main']
    paths:
      - '**/*.yml'
      - '**/*.yaml'
jobs:
  yamllint:
    name: 'Yamllint'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'                                                        # v4.2.2
        uses: 'actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683'
        with:
          fetch-depth: 0

      - name: 'Yamllint'                                                        # v2.1.1
        uses: 'karancode/yamllint-github-action@4052d365f09b8d34eb552c363d1141fd60e2aeb2'
        with:
          yamllint_file_or_dir: './'
          yamllint_strict: true
          yamllint_comment: true
          yamllint_config_filepath: '.github/workflows/yamllint.conf'
